import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Contact from '../components/contact';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body bgcolor="#85DCB">
        <center><h1>CONTACT FORM</h1></center>
      </body>

      <Contact></Contact>
  </div>
  )
}
